version: '3.8'
services:
  CodeProjectAI:
    image: codeproject/ai-server:gpu
    container_name: CodeProject.AI
    ports:
      - 32168:32168
    volumes:
      - ~/DockerVolumes/codeproject/etc/ai:/etc/codeproject/ai
      - ~/DockerVolumes/codeproject/opt/ai:/app/modules
    restart: unless-stopped
  
  mosquitto:
    image: eclipse-mosquitto:latest
    restart: always
    volumes:
      - /home/hugo/DockerVolumes/mosquitto/config:/mosquitto/config
      - /home/hugo/DockerVolumes/mosquitto/data:/mosquitto/data
      - /home/hugo/DockerVolumes/mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001
    networks:
      - iot-network

  mysql:
    image: mysql:latest
    volumes:
      #- ~/DockerVolumes/MySQL/config/my.cnf:/etc/mysql/my.cnf
      - ~/DockerVolumes/MySQL/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
    ports:
      - "3306:3306"
    networks:
      - iot-network

networks:
  iot-network:
      driver: bridge