version: '3'
services:
  CodeProjectAI:
    image: codeproject/ai-server:gpu
    container_name: CodeProject.AI
    ports:
      - 32168:32168
    volumes:
      - ~/DockerVolumes/codeproject/etc/ai:/etc/codeproject/ai
      - ~/DockerVolumes/codeproject/opt/ai:/app/modules
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
  
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    environment:
      - TZ=America/Montreal  # Set the timezone for Montreal
    volumes:
      - /home/pi/volumes/mosquitto/config:/mosquitto/config
      - /home/pi/volumes/mosquitto/data:/mosquitto/data
      - /home/pi/volumes/mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001
    restart: unless-stopped

  mysql:
    image: mysql:latest
    volumes:
      #- ~/DockerVolumes/MySQL/config/my.cnf:/etc/mysql/my.cnf
      - ~/DockerVolumes/MySQL/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
    ports:
      - "3306:3306"
    networks:
      - iot-network

networks:
  iot-network:
    driver: bridge